### PR TITLE
Add function to add plural and context to existing entry

### PR DESCRIPTION
**Pull request by Ben-Ho**

### CODE REVIEW

**Comment by Ben-Ho** [comment]
Checked your latest version and found createNew option in updateEntry-method. Now I'm using this instead of the other fork.

**Comment by Ben-Ho** [comment]
Could you please give me some feedback on my changes?

**Comment by raulferras** [comment]
Sorry, I missunderstood you and thought you discarded the pull-request due to finding the features you need in the last version. I will check your changes soon

**Comment by raulferras** [comment]
Although, I agree with the naming `setEntryXXX` you've used (I'm planning to use that in new major version), could we use `updateEntryPlurals` and `updateEntryContext` instead to follow current naming? I don't see any other problems ;)

**Comment by Ben-Ho** [comment]
No problem, changed it :)

**Pull request merged**
